# Generated by Django 5.1.4 on 2026-08-22 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_number', models.CharField(max_length=16, unique=True)),
                ('segment', models.CharField(choices=[('RETAIL', 'Retail'), ('PREMIUM', 'Premium'), ('BUSINESS', 'Business')], default='RETAIL', max_length=16)),
                ('preferred_currency', models.CharField(default='USD', max_length=3)),
                ('marketing_opt_in', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
