# Generated by Django 5.1.4 on 2026-08-23 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer_address'),
        ('managerops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='managerops.bankbranch'),
        ),
        migrations.AddField(
            model_name='customer',
            name='monthly_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='occupation',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('RESTRICTED', 'Restricted'), ('DORMANT', 'Dormant'), ('UNDER_REVIEW', 'Under review'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=16),
        ),
    ]
