# Generated by Django 5.1.4 on 2026-08-22 23:13

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=16, unique=True)),
                ('branch', models.CharField(default='0001', max_length=8)),
                ('type', models.CharField(choices=[('CHECKING', 'Checking'), ('SAVINGS', 'Savings'), ('SALARY', 'Salary'), ('JOINT', 'Joint'), ('BUSINESS', 'Business')], default='CHECKING', max_length=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('BLOCKED', 'Blocked'), ('SUSPENDED', 'Suspended'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=10)),
                ('tx_limit', models.DecimalField(decimal_places=2, default=Decimal('5000.00'), max_digits=14)),
                ('daily_limit', models.DecimalField(decimal_places=2, default=Decimal('10000.00'), max_digits=14)),
                ('blocked_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=19)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('bank_name', models.CharField(default='Bankio', max_length=80)),
                ('account_number', models.CharField(max_length=24)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('is_external', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
