# Generated by Django 5.1.4 on 2026-08-23 10:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('ledger', '0003_journalentry_currency_ledgeraccount_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='account',
            constraint=models.CheckConstraint(condition=models.Q(('blocked_amount__gte', 0)), name='account_blocked_amount_nonnegative'),
        ),
    ]
