from django.urls import include, path

from . import admin_views, app_views, views

urlpatterns = [
    path("", include("apps.portal.urls")),
    path("app/", views.dashboard_view, name="dashboard"),
    path("app/analytics/", app_views.analytics, name="app_analytics"),
    path("app/accounts/", app_views.accounts_view, name="app_accounts"),
    path("app/accounts/<int:account_id>/statement/", app_views.account_statement_view, name="app_account_statement"),
    path("app/accounts/<int:account_id>/statement/export.csv", app_views.account_statement_export, name="app_account_statement_export"),
    path("app/accounts/<int:account_id>/statement/print/", app_views.account_statement_print, name="app_account_statement_print"),
    path("app/transactions/", app_views.transactions_view, name="app_transactions"),
    path("app/transactions/<str:reference>/", app_views.transaction_detail_view, name="app_transaction_detail"),
    path("app/receipts/<str:reference>/", app_views.transaction_receipt_view, name="app_transaction_receipt"),
    path("app/investments/", app_views.investments_view, name="app_investments"),
    path("app/cards/", app_views.cards_view, name="app_cards"),
    path("app/cards/<int:card_id>/", app_views.card_detail_view, name="app_card_detail"),
    path("app/cards/<int:card_id>/controls/", app_views.card_control_view, name="app_card_control"),
    path("app/cards/<int:card_id>/transactions/", app_views.card_transactions_view, name="app_card_transactions"),
    path("app/cards/<int:card_id>/transactions/<int:tx_id>/", app_views.card_transaction_detail_view, name="app_card_transaction_detail"),
    path("app/cards/<int:card_id>/invoices/", app_views.card_invoices_view, name="app_card_invoices"),
    path("app/cards/<int:card_id>/invoices/<int:statement_id>/", app_views.card_invoice_detail_view, name="app_card_invoice_detail"),
    path("app/cards/<int:card_id>/invoices/pay/", app_views.card_pay_invoice_view, name="app_card_pay_invoice"),
    path("app/security/", app_views.security_view, name="app_security"),
    path("app/settings/", app_views.settings_view, name="app_settings"),
    path("app/tour/replay/", app_views.tour_replay_view, name="app_tour_replay"),
    path("app/tour/<str:outcome>/", app_views.tour_finish_view, name="app_tour_finish"),
    path("app/notifications/", app_views.notifications_view, name="app_notifications"),
    path("app/notifications/<int:notification_id>/read/", app_views.notification_read_view, name="app_notification_read"),
    path("app/notifications/read-all/", app_views.notifications_mark_all_read_view, name="app_notifications_mark_all_read"),
    path("login/", views.login_view, name="login"),
    path("otp/", views.otp_verify_view, name="otp_verify"),
    path("logout/", views.logout_view, name="logout"),
    path("", include("apps.transfers.urls")),
    path("", include("apps.managerops.urls")),
    path("manage/users/", admin_views.users_list, name="admin_users"),
    path("manage/users/dashboard/", admin_views.admin_dashboard, name="admin_dashboard"),
    path("manage/users/new/", admin_views.user_create, name="admin_user_create"),
    path("manage/users/<int:user_id>/", admin_views.user_detail, name="admin_user_detail"),
    path("manage/users/<int:user_id>/block/", admin_views.user_block, name="admin_user_block"),
    path("manage/users/<int:user_id>/unblock/", admin_views.user_unblock, name="admin_user_unblock"),
]
