# Generated by Django 5.1.4 on 2026-08-23 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('PREMIUM_CUSTOMER', 'Premium Customer'), ('MANAGER', 'Manager'), ('CARD_OPS_ANALYST', 'Card Operations Analyst'), ('COMPLIANCE_ANALYST', 'Compliance Analyst'), ('FRAUD_ANALYST', 'Fraud Analyst'), ('SENIOR_FRAUD_ANALYST', 'Senior Fraud Analyst'), ('FRAUD_MANAGER', 'Fraud Manager'), ('SUPPORT_AGENT', 'Support Agent'), ('ADMIN', 'Administrator'), ('AUDITOR', 'Auditor')], default='CUSTOMER', max_length=30),
        ),
    ]
