# Generated by Django 5.1.4 on 2026-08-24 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0003_sessionrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
