# Generated by Django 5.1.4 on 2026-08-26 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0004_user_otp_generated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_version', models.CharField(max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('skipped_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tour_progress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
