# Generated by Django 5.1.4 on 2026-08-23 13:37

import apps.fraud.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(db_index=True, max_length=64)),
                ('resource_reference', models.CharField(blank=True, max_length=200)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('risk_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('risk_level', models.CharField(blank=True, choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=10)),
                ('decision', models.CharField(choices=[('PENDING', 'evaluation in flight'), ('ALLOW', 'Allow'), ('CHALLENGE', 'Challenge'), ('REVIEW', 'Review'), ('BLOCK', 'Block'), ('DEFER', 'dependency unavailable')], default='PENDING', max_length=10)),
                ('engine_mode', models.CharField(choices=[('SHADOW', 'Shadow'), ('CHALLENGE_ONLY', 'Challenge Only'), ('ENFORCEMENT', 'Enforcement')], max_length=20)),
                ('status', models.CharField(choices=[('EVALUATING', 'Evaluating'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='EVALUATING', max_length=12)),
                ('policy_version', models.CharField(blank=True, max_length=40)),
                ('ruleset_version', models.CharField(blank=True, max_length=40)),
                ('triggered_rules', models.JSONField(blank=True, default=list)),
                ('signal_values', models.JSONField(blank=True, default=dict)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_evaluations', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FraudAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(max_length=64)),
                ('severity', models.CharField(default='MEDIUM', max_length=10)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ACKNOWLEDGED', 'Acknowledged'), ('ESCALATED', 'Escalated'), ('CLOSED', 'Closed')], default='OPEN', max_length=14)),
                ('dedup_key', models.CharField(blank=True, db_index=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engine_alerts', to=settings.AUTH_USER_MODEL)),
                ('evaluation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fraud.riskevaluation')),
            ],
        ),
        migrations.CreateModel(
            name='RiskRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_id', models.SlugField(max_length=64)),
                ('version', models.PositiveIntegerField(default=1)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('enabled', models.BooleanField(default=False)),
                ('lifecycle', models.CharField(choices=[('DRAFT', 'Draft'), ('TESTING', 'Testing'), ('APPROVED', 'Approved'), ('ACTIVE', 'Active'), ('RETIRED', 'Retired')], default='DRAFT', max_length=10)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('operation_types', models.JSONField(default=list)),
                ('conditions', models.JSONField(default=dict)),
                ('score', models.PositiveSmallIntegerField()),
                ('severity', models.CharField(default='MEDIUM', max_length=10)),
                ('effective_from', models.DateTimeField(blank=True, null=True)),
                ('effective_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['priority', 'id'],
                'constraints': [models.UniqueConstraint(fields=('rule_id', 'version'), name='uniq_rule_id_version'), models.CheckConstraint(condition=models.Q(('score__lte', 100)), name='riskrule_score_bounds')],
            },
        ),
        migrations.CreateModel(
            name='RiskSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_id', models.CharField(max_length=64)),
                ('value', models.JSONField()),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='fraud.riskevaluation')),
            ],
        ),
        migrations.CreateModel(
            name='FraudCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_reference', models.CharField(default=apps.fraud.models.new_case_reference, max_length=32, unique=True)),
                ('severity', models.CharField(default='MEDIUM', max_length=10)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('INVESTIGATING', 'Investigating'), ('WAITING_CUSTOMER', 'Waiting Customer'), ('ESCALATED', 'Escalated'), ('CONFIRMED_FRAUD', 'Confirmed Fraud'), ('FALSE_POSITIVE', 'False Positive'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('summary', models.TextField(blank=True)),
                ('decision_reason', models.TextField(blank=True)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('alerts', models.ManyToManyField(blank=True, related_name='cases', to='fraud.fraudalert')),
                ('assigned_analyst', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fraud_cases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('status', 'CLOSED'), _negated=True), models.Q(('decision_reason', ''), _negated=True), _connector='OR'), name='fraudcase_closed_requires_reason')],
            },
        ),
        migrations.AddIndex(
            model_name='riskevaluation',
            index=models.Index(fields=['operation_type', '-created_at'], name='fraud_riske_operati_008e18_idx'),
        ),
        migrations.AddIndex(
            model_name='riskevaluation',
            index=models.Index(fields=['decision', '-created_at'], name='fraud_riske_decisio_1ada84_idx'),
        ),
        migrations.AddConstraint(
            model_name='riskevaluation',
            constraint=models.CheckConstraint(condition=models.Q(('risk_score__isnull', True), ('risk_score__lte', 100), _connector='OR'), name='riskevaluation_score_bounds'),
        ),
        migrations.AddConstraint(
            model_name='riskevaluation',
            constraint=models.CheckConstraint(condition=models.Q(('decision', ''), _negated=True), name='riskevaluation_decision_valid'),
        ),
        migrations.AddConstraint(
            model_name='risksignal',
            constraint=models.UniqueConstraint(fields=('evaluation', 'signal_id'), name='uniq_signal_per_evaluation'),
        ),
    ]
