# Generated by Django 5.1.4 on 2026-08-23 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fraud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risksignal',
            name='value',
            field=models.JSONField(null=True),
        ),
    ]
