# Generated by Django 5.1.4 on 2026-08-23 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fraud', '0002_alter_risksignal_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='FraudEngineSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('value', models.CharField(max_length=40)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
