# Generated by Django 5.1.4 on 2026-08-23 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fraud', '0003_fraudenginesetting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_hash', models.CharField(max_length=64)),
                ('code_hash', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('CONSUMED', 'Consumed'), ('EXPIRED', 'Expired')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_challenges', to=settings.AUTH_USER_MODEL)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='fraud.riskevaluation')),
            ],
            options={
                'indexes': [models.Index(fields=['customer', 'status'], name='fraud_riskc_custome_6563cd_idx')],
            },
        ),
    ]
