# Generated by Django 5.1.4 on 2026-08-23 00:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=24, unique=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('current_step', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('IDENTITY_REVIEW', 'Identity Review'), ('KYC_REVIEW', 'Kyc Review'), ('ADDITIONAL_INFORMATION_REQUIRED', 'Additional Information Required'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ACCOUNT_CREATED', 'Account Created')], default='DRAFT', max_length=36)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('products', models.JSONField(blank=True, default=list)),
                ('resume_token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('risk_level', models.CharField(choices=[('LOW', 'LOW'), ('MEDIUM', 'MEDIUM'), ('HIGH', 'HIGH')], default='LOW', max_length=8)),
                ('decision_reason', models.CharField(blank=True, max_length=255)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='portal_application', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='portal_applications_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['email'], name='portal_acco_email_480d98_idx'), models.Index(fields=['status'], name='portal_acco_status_7fb7c3_idx')],
            },
        ),
    ]
