# Generated by Django 5.1.4 on 2026-08-23 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountapplication',
            name='temp_password',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
