# Generated by Django 5.1.4 on 2026-08-22 23:13

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('DEBIT_CARD', 'Debit'), ('CREDIT_CARD', 'Credit'), ('VIRTUAL_CARD', 'Virtual'), ('TEMPORARY_VIRTUAL_CARD', 'Temp Virtual'), ('SINGLE_USE_CARD', 'Single Use')], default='DEBIT_CARD', max_length=32)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('FROZEN', 'Frozen'), ('BLOCKED', 'Blocked'), ('EXPIRED', 'Expired'), ('REPLACED', 'Replaced')], default='ACTIVE', max_length=10)),
                ('last4', models.CharField(max_length=4)),
                ('holder_name', models.CharField(max_length=120)),
                ('expiry_month', models.PositiveSmallIntegerField(default=12)),
                ('expiry_year', models.PositiveSmallIntegerField(default=2030)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('tx_limit', models.DecimalField(decimal_places=2, default=Decimal('2000.00'), max_digits=14)),
                ('daily_limit', models.DecimalField(decimal_places=2, default=Decimal('3000.00'), max_digits=14)),
                ('online_enabled', models.BooleanField(default=True)),
                ('international_enabled', models.BooleanField(default=False)),
                ('contactless_enabled', models.BooleanField(default=True)),
                ('atm_enabled', models.BooleanField(default=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cards', to='accounts.account')),
            ],
        ),
        migrations.CreateModel(
            name='CardTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant', models.CharField(max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('international', models.BooleanField(default=False)),
                ('online', models.BooleanField(default=False)),
                ('declined', models.BooleanField(default=False)),
                ('decline_reason', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='cards.card')),
                ('journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ledger.journalentry')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CreditStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=19)),
                ('paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='statements', to='cards.card')),
            ],
            options={
                'unique_together': {('card', 'period_end')},
            },
        ),
    ]
