# Generated by Django 5.1.4 on 2026-08-25 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_cardrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditstatement',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
