# Generated by Django 5.1.4 on 2026-08-23 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_db_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='ledgeraccount',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('BLOCKED', 'Blocked'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='ledgeraccount',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['ACTIVE', 'BLOCKED', 'CLOSED'])), name='ledgeraccount_status_valid'),
        ),
    ]
