# Generated by Django 5.1.4 on 2026-08-23 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0004_posted_journal_immutability'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerIdempotencyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=160, unique=True)),
                ('operation', models.CharField(max_length=64)),
                ('result', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='idempotency_records', to='ledger.journalentry')),
            ],
        ),
    ]
