# Generated by Django 5.1.4 on 2026-08-23 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0005_ledgeridempotencyrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='chain_hash',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='payload_hash',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='previous_entry_hash',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True),
        ),
    ]
