# Generated by Django 5.1.4 on 2026-08-23 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0006_journalentry_chain_hash_journalentry_payload_hash_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerProofBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveBigIntegerField(unique=True)),
                ('first_journal_id', models.PositiveBigIntegerField()),
                ('last_journal_id', models.PositiveBigIntegerField()),
                ('entry_count', models.PositiveIntegerField()),
                ('merkle_root', models.CharField(max_length=64)),
                ('previous_batch_hash', models.CharField(max_length=64)),
                ('batch_manifest_hash', models.CharField(blank=True, max_length=64)),
                ('canonicalization_version', models.CharField(max_length=32)),
                ('hash_algorithm', models.CharField(default='SHA-256', max_length=32)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('SEALED', 'Sealed'), ('ANCHORED', 'Anchored'), ('VERIFIED', 'Verified'), ('FAILED', 'Failed')], default='SEALED', max_length=10)),
                ('signature', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sealed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('first_journal_id__lte', models.F('last_journal_id'))), name='proofbatch_range_valid')],
            },
        ),
    ]
