# Generated by Django 5.1.4 on 2026-08-23 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0007_ledgerproofbatch'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerAnchor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=64)),
                ('anchor_reference', models.CharField(blank=True, max_length=128)),
                ('idempotency_key', models.CharField(max_length=200, unique=True)),
                ('commitment', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('SUBMITTED', 'Submitted'), ('CONFIRMING', 'Confirming'), ('CONFIRMED', 'Confirmed'), ('FAILED', 'Failed'), ('SUPERSEDED', 'Superseded')], default='CREATED', max_length=12)),
                ('error', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='anchors', to='ledger.ledgerproofbatch')),
            ],
        ),
    ]
