# Generated by Django 5.1.4 on 2026-08-23 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0008_ledgeranchor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgeranchor',
            name='idempotency_key',
            field=models.CharField(max_length=200),
        ),
    ]
