# Generated by Django 5.1.4 on 2026-08-22 23:13

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('ledger', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('type', models.CharField(choices=[('PERSONAL', 'Personal Loan'), ('AUTO', 'Auto Loan'), ('MORTGAGE', 'Mortgage')], max_length=12)),
                ('min_amount', models.DecimalField(decimal_places=2, default=Decimal('1000'), max_digits=14)),
                ('max_amount', models.DecimalField(decimal_places=2, default=Decimal('50000'), max_digits=14)),
                ('base_rate', models.DecimalField(decimal_places=2, default=Decimal('9.99'), max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('term_months', models.PositiveSmallIntegerField(default=12)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(choices=[('DRAFT', 'Simulation'), ('SUBMITTED', 'Application'), ('REVIEW', 'Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ACTIVE', 'Active'), ('PAID', 'Paid'), ('DEFAULTED', 'Defaulted')], default='DRAFT', max_length=10)),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loan_applications', to=settings.AUTH_USER_MODEL)),
                ('disbursed_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.account')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lending.loanproduct')),
            ],
        ),
        migrations.CreateModel(
            name='RepaymentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_no', models.PositiveSmallIntegerField()),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule', to='lending.loanapplication')),
                ('journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ledger.journalentry')),
            ],
            options={
                'ordering': ['installment_no'],
                'unique_together': {('application', 'installment_no')},
            },
        ),
    ]
