# Generated by Django 5.1.4 on 2026-08-23 00:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountNumberCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_code', models.CharField(max_length=8, unique=True)),
                ('last', models.BigIntegerField(default=100000000)),
            ],
        ),
        migrations.CreateModel(
            name='AccountRestriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restriction_type', models.CharField(choices=[('DEBIT_BLOCK', 'Debit block'), ('CREDIT_BLOCK', 'Credit block'), ('TRANSFER_BLOCK', 'Transfer block'), ('CARD_BLOCK', 'Card block'), ('FULL_BLOCK', 'Full block'), ('AML_HOLD', 'AML hold'), ('LEGAL_HOLD', 'Legal hold')], max_length=16)),
                ('reason', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('effective_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='restrictions', to='accounts.account')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_type', models.CharField(choices=[('GENERAL_SERVICE', 'General'), ('ACCOUNT_OPENING', 'Account opening'), ('CREDIT_REVIEW', 'Credit review'), ('INVESTMENT_REVIEW', 'Investment review'), ('LOAN_REVIEW', 'Loan review'), ('KYC_UPDATE', 'KYC update')], default='GENERAL_SERVICE', max_length=20)),
                ('scheduled_at', models.DateTimeField()),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('completed', models.BooleanField(default=False)),
                ('canceled', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_appointments', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('ACCOUNT_OPENING', 'Account opening'), ('LIMIT_INCREASE', 'Transfer limit increase'), ('CREDIT_CARD_LIMIT', 'Credit card limit'), ('LOAN_APPROVAL', 'Loan approval'), ('ACCOUNT_UNBLOCK', 'Account unblock'), ('ACCOUNT_CLOSURE', 'Account closure'), ('FEE_WAIVER', 'Fee waiver'), ('RATE_EXCEPTION', 'Rate exception'), ('OVERDRAFT', 'Overdraft facility'), ('HIGH_RISK_CUSTOMER', 'High-risk customer acceptance'), ('ADJUSTMENT_REQUEST', 'Financial adjustment')], max_length=24)),
                ('resource_type', models.CharField(blank=True, max_length=64)),
                ('resource_id', models.CharField(blank=True, max_length=64)),
                ('required_level', models.CharField(choices=[('RELATIONSHIP_MANAGER', 'Relationship Manager'), ('BRANCH_MANAGER', 'Branch Manager'), ('SENIOR_MANAGER', 'Senior Manager'), ('REGIONAL_MANAGER', 'Regional Manager')], max_length=24)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('current_value', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELED', 'Canceled'), ('EXPIRED', 'Expired')], default='PENDING', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approvals_requested', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approvals_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BankBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_code', models.CharField(max_length=8, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('region', models.CharField(default='CENTER', max_length=60)),
                ('status', models.CharField(default='ACTIVE', max_length=10)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='managed_branches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AccountApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(max_length=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('business_name', models.CharField(blank=True, max_length=140)),
                ('registration_number', models.CharField(blank=True, max_length=32)),
                ('state', models.CharField(default='APPLICATION', max_length=18)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.account')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_applications', to=settings.AUTH_USER_MODEL)),
                ('joint_with', models.ManyToManyField(blank=True, related_name='joint_applications', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='managerops.bankbranch')),
            ],
        ),
        migrations.CreateModel(
            name='FeeWaiverRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee', models.CharField(max_length=64)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.CharField(max_length=255)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_waivers', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ManagerNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='GENERAL', max_length=32)),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_notes', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ManagerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('RELATIONSHIP_MANAGER', 'Relationship Manager'), ('BRANCH_MANAGER', 'Branch Manager'), ('SENIOR_MANAGER', 'Senior Manager'), ('REGIONAL_MANAGER', 'Regional Manager')], default='RELATIONSHIP_MANAGER', max_length=24)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='managers', to='managerops.bankbranch')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manager_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('CARD_REPLACEMENT', 'Card replacement'), ('ACCOUNT_STATEMENT', 'Statement'), ('LIMIT_CHANGE', 'Limit change'), ('ACCOUNT_CLOSURE', 'Closure'), ('CONTACT_UPDATE', 'Contact update'), ('ACCOUNT_REACTIVATION', 'Reactivation'), ('PRODUCT_CHANGE', 'Product change')], max_length=24)),
                ('detail', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('WAITING_CUSTOMER', 'Waiting Customer'), ('COMPLETED', 'Completed'), ('CANCELED', 'Canceled')], default='OPEN', max_length=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to=settings.AUTH_USER_MODEL)),
                ('opened_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerManagerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='ACTIVE', max_length=10)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='managerops.bankbranch')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_assignments', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='portfolio_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('customer', 'manager')},
            },
        ),
    ]
