# Generated by Django 5.1.4 on 2026-08-23 00:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managerops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalrequest',
            name='operation_type',
            field=models.CharField(choices=[('ACCOUNT_OPENING', 'Account opening'), ('LIMIT_INCREASE', 'Transfer limit increase'), ('CREDIT_CARD_LIMIT', 'Credit card limit'), ('LOAN_APPROVAL', 'Loan approval'), ('ACCOUNT_UNBLOCK', 'Account unblock'), ('ACCOUNT_CLOSURE', 'Account closure'), ('FEE_WAIVER', 'Fee waiver'), ('RATE_EXCEPTION', 'Rate exception'), ('OVERDRAFT', 'Overdraft facility'), ('HIGH_RISK_CUSTOMER', 'High-risk customer acceptance'), ('ADJUSTMENT_REQUEST', 'Financial adjustment'), ('ONBOARDING_REVIEW', 'Public onboarding review')], max_length=24),
        ),
        migrations.AlterField(
            model_name='approvalrequest',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approvals_requested', to=settings.AUTH_USER_MODEL),
        ),
    ]
